FROM node:chakracore-10.13.0

WORKDIR /usr/src/app

COPY package-lock.json package-lock.json
COPY package.json package.json
RUN npm install && npm install -g truffle@4.1.14
COPY . .


EXPOSE 3000
EXPOSE 8545
CMD [ "bash" ]
