resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.12"
- name: semver
  type: docker-image
  source:
    repository: "concourse/semver-resource"
    tag: "1.0.2"
- name: s3
  type: docker-image
  source:
    repository: "concourse/s3-resource"
    tag: "1.0.2"
resources:
- name: kubernetes-production
  type: kubernetes
  icon: application-import
  source:
    server: ((generated_cluster_address))
    namespace: ((generated_serviceaccount_namespace))
    token: ((generated_serviceaccount_token))
    certificate_authority: ((generated_serviceaccount_ca))

- name: truffle-docker-image
  type: docker-image
  icon: docker
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-registry))/((docker-hub-orgname))/incident-reporting-truffle
- name: ui-docker-image
  type: docker-image
  icon: docker
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-registry))/((docker-hub-orgname))/incident-reporting-ui

- name: contract-address-s3
  type: s3
  source:
    bucket: applications
    endpoint: ((s3-semver-endpoint))
    regexp: contract-address-(.*)
    # access_key_id: test
    access_key_id: ((s3-semver-key-id))
    secret_access_key: ((s3-semver-access-key))
    disable_ssl: true
    # skip_download: true
    # disable_multipart: true
    # use_v2_signing: false
    initial_path: contract-address-0.0.0
    initial_content_text: "testing"

- name: ui-version
  icon: weather-sunset
  type: semver
  source:
    driver: s3
    initial_version: ((s3-semver-initial-version))
    endpoint: ((s3-semver-endpoint))
    bucket: ((s3-semver-bucket))
    key: ui-version
    access_key_id: ((s3-semver-key-id))
    secret_access_key: ((s3-semver-access-key))
    disable_ssl: ((s3-semver-disable-ssl))

- name: truffle-version
  icon: weather-sunset
  type: semver
  source:
    driver: s3
    initial_version: ((s3-semver-initial-version))
    endpoint: ((s3-semver-endpoint))
    bucket: ((s3-semver-bucket))
    key: ui-version
    access_key_id: ((s3-semver-key-id))
    secret_access_key: ((s3-semver-access-key))
    disable_ssl: ((s3-semver-disable-ssl))

- name: contract-version
  icon: weather-sunset
  type: semver
  source:
    driver: s3
    initial_version: ((s3-semver-initial-version))
    endpoint: ((s3-semver-endpoint))
    bucket: ((s3-semver-bucket))
    key: incident-reporting-contract-version
    access_key_id: ((s3-semver-key-id))
    secret_access_key: ((s3-semver-access-key))
    disable_ssl: ((s3-semver-disable-ssl))

- name: incident-reporting-truffle
  icon: github-face
  type: git
  source:
    uri: https://github.com/vmware-samples/incident-reporting.git
    branch: ((code-branch))
    paths:
      - truffle
- name: incident-reporting-ui
  icon: github-face
  type: git
  source:
    uri: https://github.com/vmware-samples/incident-reporting.git
    branch: ((code-branch))
    paths:
      - ui-server

- name: incident-reporting-kubernetes
  icon: github-face
  type: git
  source:
    uri: https://github.com/vmware-samples/incident-reporting.git
    branch: ((code-branch))
    paths:
      - deployment/kubernetes/*.yml
      - deployment/kubernetes/*.yaml

jobs:

  - name: truffle-tests
    plan:
      - get: incident-reporting-truffle
        trigger: true
      - task: run truffle tests
        config:
          inputs:
            - name: incident-reporting-truffle
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: chakracore-10.13.0
          run:
            path: sh
            args:
              - -x
              - -c
              - "pwd; ls -al ; cd incident-reporting-truffle/truffle; ls -al; npm install && npm install -g truffle@4.1.14 && truffle test"

  - name: create-secrets
    serial: true
    plan:
      - aggregate:
        - get: contract-address-s3
          trigger: true
        - get: incident-reporting-kubernetes
      - task: create secret reseource
        config:
          inputs:
            - name: contract-address-s3
            - name: incident-reporting-kubernetes
          outputs:
            - name: secret
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag:  3.9
          run:
            path: sh
            args:
              - -xc
              - |
                ls -al
                u=((client_user))
                p=((client_password))
                url=((client_url))

                ls -alrt contract-address-s3/
                cat contract-address-s3/contract-address-*
                c=$(cat contract-address-s3/contract-address-*)

                cat <<-EOF > secret/secret.yaml
                ---
                apiVersion: v1
                kind: Secret
                metadata:
                  name: incident-reporting-secrets
                  labels:
                    app: incident-reporting-ui
                data:
                  user: `printf $u | base64`
                  password: `printf $p | base64`
                  url: `printf $url | base64 | tr -d '\n'`
                  contractAddres: `printf $c | base64`
                EOF
                cat secret/secret.yaml | od -c
      - put: kubernetes-production
        params:
          kubectl: apply -f secret/secret.yaml  -n ansible-namespace
      - put: kubernetes-production
        params:
          kubectl: create secret docker-registry incident-reporting-registry-cred --docker-server=((docker-hub-registry)) --docker-username=((docker-hub-username)) --docker-password=((docker-hub-password))

  - name: deploy-ui
    plan:
      - aggregate:
        - get: contract-address-s3
          passed: [deploy-contract]
        - get: incident-reporting-kubernetes
          trigger: true
      - put: kubernetes-production
        params:
          kubectl: apply -f incident-reporting-kubernetes/deployment/kubernetes -n ansible-namespace
          wait_until_ready_selector: app=incident-reporting-ui

  - name: deploy-contract
    public: true
    serial: true
    plan:
      - get: contract-version
        params: {bump: patch}
      - get: truffle-docker-image
        trigger: true
      - task: run truffle deploy
        image: truffle-docker-image
        config:
          platform: linux
          inputs:
            - name: contract-version
          outputs:
            - name: deploy-output
          run:
            path: sh
            args:
              - -xc
              - |
                # set -eu
                version=$(cat contract-version/version)
                build_dir=$PWD;
                mkdir $build_dir/work

                cd /usr/src/app;
                truffle deploy --network production --reset | tee $build_dir/work/output;
                cd $build_dir
                ls -alrth;
                echo "should see deploy-output"

                cat work/output | sed -e '/IncidentLog:/!d; s/^.*: //' > deploy-output/contract-address-${version}
                ls -alrt deploy-output

          params:
            PRODUCTION_URL: "https://((client_user)):((client_password))@((client_url))"
      - aggregate:
        - put: contract-address-s3
          params:
            file: deploy-output/contract-address-*
        - put: contract-version
          params: {bump: patch}


## Container builds
## -----------------
  - name: build-image-ui
    public: true
    serial: true
    plan:
    - aggregate:
      - get: ui-version
        params: {bump: patch}
      - get: incident-reporting-ui
        trigger: true
    - put: ui-docker-image
      params:
        tag_file: ui-version/version
        tag_as_latest: true
        build: incident-reporting-ui
        dockerfile: incident-reporting-ui/ui-server/Dockerfile
    - put: ui-version
      params: {bump: patch}

  # - name: build-image-truffle
  #   public: true
  #   serial: true
  #   plan:
  #   - aggregate:
  #     - get: truffle-version
  #       params: {bump: patch}
  #     - get: incident-reporting-truffle
  #       trigger: true
  #       passed: [truffle-tests]
  #   - put: truffle-docker-image
  #     params:
  #       tag_file: tag-holder/tag
  #       tag_as_latest: true
  #       build: incident-reporting-truffle
  #       dockerfile: incident-reporting-truffle/truffle/Dockerfile
  #   - put: truffle-version
  #     params: {bump: patch}
