resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.12"

resources:
- name: kubernetes-production
  type: kubernetes
  source:
    server: https://api.incident-reporting-724e9f80-6826-11e9-b4e4-0e7c7c059320.57197a32-43f3-46f6-bd80-bc65267b6d7c.vke-user.com
    namespace: ((generated_serviceaccount_namespace))
    token: ((generated_serviceaccount_token))
    certificate_authority: ((generated_serviceaccount_ca))
- name: incident-reporting
  type: git
  source:
    uri: https://github.com/vmware-samples/incident-reporting.git
    branch: master
jobs:
  - name: kubernetes-deploy-production
    plan:
      - get: incident-reporting
        trigger: true
      - put: kubernetes-production
        params:
          kubectl: apply -f incident-reporting/deployment/kubernetes
          wait_until_ready_selector: app=incident-reporting